$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: taxi-batch-mlflow-env
description: Environment for batch inference using MLflow model dependencies
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
conda_file: conda.yml
