$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: taxi-batch-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: batch-conda.yml
description: Custom environment for batch inference with controlled dependencies
