channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow==2.9.2
      - mlflow-skinny==2.9.2
      - protobuf==3.20.3
      - azureml-mlflow==1.57.0
      - azureml-sdk==1.57.0
      - azure-identity==1.19.0
      - azureml-core==1.57.0
      - pyarrow==14.0.2
      - scikit-learn==1.5.2
      - pandas==2.2.3
      - joblib==1.4.2
      - matplotlib==3.9.2
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector