# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

resources:
  repositories:
    - repository: mlops-templates
      name: Azure/mlops-templates
      endpoint: github-connection
      type: github
      ref: feature/feathr #branch name

stages:
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
      - job: CreateStorageForTerraform
        displayName: Create Storage for Terraform
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/infra/create-resource-group.yml@mlops-templates
          - template: templates/infra/create-storage-account.yml@mlops-templates
          - template: templates/infra/create-storage-container.yml@mlops-templates
  - stage: DeployAzureMachineLearningRG
    displayName: Deploy AML Workspace
    jobs:
      - job: DeployAMLWorkspace
        displayName: Deploy Terraform
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/infra/create-sp-variables.yml@mlops-templates
          - template: templates/infra/install-terraform.yml@mlops-templates
          # required to create the userroles table in SQL for feature store, should be pushed to the app for creation
          # for now as the app does not create, remove later: https://github.com/feathr-ai/feathr/tree/2cf23a510ff1ed523026b81eabde60b35456b8af/registry/access_control#initialize-userroles-records
          - template: templates/infra/install-mssql-cli.yml@mlops-templates
          - template: templates/infra/run-terraform-init.yml@mlops-templates
          - template: templates/infra/run-terraform-validate.yml@mlops-templates
          - template: templates/infra/run-terraform-plan.yml@mlops-templates
          - template: templates/infra/run-terraform-apply.yml@mlops-templates
