variables:
- template: ../../../config-aml.yml
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../../config-infra-dev.yml

trigger:
- none

pool:
  vmImage: $(ap_vm_image)


stages :
  - stage: Lint
    displayName: Lint and Preflight check
    jobs:
    - job: LintBicep
      displayName: Lint Bicep Code
      steps:
        - checkout: self
        - script: |
            az bicep build --file ./infrastructure/bicep/main.bicep
          name: LintBicepCode
          displayName: Run Bicep Linter

  - stage: PreflightValidation
    jobs:
    - job: ValidateBicepCode
      displayName: Validate Bicep Code
      steps:
        - task: AzureCli@2
          name: RunPreflightValidateion
          displayName: Run Preflight Validation
          inputs:
            azureSubscription: $(ado_service_connection_rg)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group validate \
                --resource-group $(resource_group) \
                --template-file ./infrastructure/bicep/main.bicep \
                --parameters location=$(location) resourceGroupName=$(resource_group) prefix=$(namespace) postfix=$(postfix)

  - stage: CheckOutBicepAndDeploy
    displayName: Deploy AML Workspace
    jobs:
    - job: DeployBicep
      displayName: Create Bicep Deployment
      steps:
      - task: AzureCLI@2
        displayName: Running Deployment
        inputs:
          azureSubscription: $(ado_service_connection_rg)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            echo "deploying bicep..."
            az deployment sub create --name $(Build.DefinitionName)    --location $(location) --template-file ./infrastructure/bicep/main.bicep --parameters location=$(location) resourceGroupName=$(resource_group) prefix=$(namespace) postfix=$(postfix)