name: deploy-cv-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  create-compute:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: gpu-cluster
        size: Standard_NC6
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  register-environment:
      needs: [get-config,create-compute]
      uses: ./.github/workflows/register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file: cv/aml-cli-v2/mlops/azureml/train/train-env.yaml 
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  register-dataset:
      needs: [get-config,register-environment]
      uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        data_file: cv/aml-cli-v2/mlops/azureml/train/create_stanford_dogs_dataset.yaml
        file_type: Training
        name: stanford_dogs
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  run-pipeline:
      needs: [get-config,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  cv/aml-cli-v2/mlops/azureml/train/pipeline.yaml
        job-name: cv-train
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
