name: deploy-batch-endpoint-pipeline

on:
  workflow_dispatch:
jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "config_env=config-infra-prod.yml" >> $GITHUB_ENV;
      - id: set-dev-branch
        name: setdevbranch
        if: ${{ github.ref != 'refs/heads/main'}}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV;
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT;
  get-config:
    needs: set-env-branch
    uses: pgabriel-01/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file}}
  create-compute:
    needs: get-config
    uses: pgabriel-01/mlops-templates/.github/workflows/create-compute.yml@main
    with:
      cluster_name: batch-cluster
      size: STANDARD_D4S_V5
      min_instances: 0
      max_instances: 5
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  create-endpoint:
    needs: [get-config, create-compute]
    uses: pgabriel-01/mlops-templates/.github/workflows/create-endpoint.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      endpoint_file: classical/aml-cli-v2/mlops/azureml/deploy/batch/batch-endpoint.yml
      endpoint_name: ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }}
      endpoint_type: batch
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  create-deployment:
    uses: pgabriel-01/mlops-templates/.github/workflows/create-deployment.yml@main
    needs: [get-config, create-endpoint]
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      endpoint_file: classical/aml-cli-v2/mlops/azureml/deploy/batch/batch-deployment.yml
      endpoint_name: ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }}
      endpoint_type: batch
      deployment_name: eptestdeploy
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
